### ISSUE TITLE
Auto enable/disable at sunset/sunrise

### ISSUE THREAD

**Issue by TheOkayJK** [0ranko0P/AutoDark#1]
An example of this behavior in code is available here. https://github.com/KieronQuinn/DarQ/blob/master/app/src/main/java/com/kieronquinn/app/darq/services/DarqBackgroundService.kt
I much prefer the simplicity of your app so if it had this feature that would be excellent!
Thanks!

**Comment by 0ranko0P** [comment]
New version released, fell free to send me your feedback.

**Comment by cvzi** [comment]
I had enabled "turn on from sunset to sunrise" switch a few weeks ago and it worked fine
After some time I noticed that the sunrise time is wrong now, it switched to early to darkmode.
I turned the switch off and on again and now the sunrise time seems to be correct again.
