### ISSUE TITLE
[Suggestion] Sunrise & Sunset Offsets

### ISSUE THREAD

**Issue by m-p-3** [0ranko0P/AutoDark#10]
Hi, would it be possible to add a manual offset to the automatic sunrise and sunset switch?

I'd actually prefer if the dark theme would toggle after the [twilight period](https://en.wikipedia.org/wiki/Twilight), when it's actually at night, and I'd personally add a 30 minutes offset to handle that. Is that something doable?

Even better would be if the app could calculate the different twilights between day and night like [civil dawn, nautical dawn, astronomical dawn](https://en.wikipedia.org/wiki/Twilight#/media/File:Twilight-dawn_subcategories.svg) as well as [civil dusk, nautical dusk, astronomical dusk](https://en.wikipedia.org/wiki/Twilight#/media/File:Twilight_subcategories.svg).

Thanks!

**Comment by 0ranko0P** [comment]
Calculate different twilights and provide these options are too complex for a tiny app, please schedule the time manually.
