### ISSUE TITLE
Permanent Dark Mode

### ISSUE THREAD

**Issue by mobiusstripe** [0ranko0P/AutoDark#11]
Would it be possible to have the application always on? 

Thanks for the app! It's way better than having to go into my settings every restart and turning on Force Dark Mode.

**Comment by 0ranko0P** [comment]
I'm glad you like my app,! it has been fixed now, check out [3.0.3](https://github.com/0ranko0P/AutoDark/releases/tag/v3.0.3) release.

**Comment by mobiusstripe** [comment]
Thank you!
