### ISSUE TITLE
Smart dark可以使用adb实现

### ISSUE THREAD

**Issue by xyf2018** [0ranko0P/AutoDark#12]
app中的实验性功能--Smart dark模式，对应的debug.hwui.force_dark属性使用adb shell权限就可以更改。可以参考darQ https://github.com/KieronQuinn/DarQ/
它的白名单功能是通过无障碍来检测app的打开关闭。

我是一直在使用darQ，但它并不支持shizuku授权。看到作者您的这款app有着相似的功能，而且已经需要了adb权限，最重要的是支持shizuku。所以建议一下可以将smart dark也用adb实现，这样就不需要root了。当然，这样的话黑名单功能可能还需要无障碍权限。

**Comment by 0ranko0P** [comment]
去年砍掉了: d1afd78efb22e0f15da0aaa375c7b77596793e76

因为重启后还得等待用户用ADB 启动Shizuku 这个过程并不可靠, 一定要用的话可以试试2.0.2 版本
