### ISSUE TITLE
dark wallpaper crash

### ISSUE THREAD

**Issue by NSTAdventure** [0ranko0P/AutoDark#13]
Realme 5i
Android Q (10) Realme UI 1.0 ColorOS v7
Autodark version: 3.0.3

no matter how many time i tried to visit dark wallpaper feature it will automatically crash the app:
FATAL EXCEPTION: main
Process: me.ranko.autodark, PID: 24523
g.b.a.f0.w.f: Unexpected exception thrown by non-Glide code
	at g.b.a.f0.w.f0$a.run(Unknown Source:9)
	at android.os.Handler.handleCallback(Handler.java:899)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7853)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
	at j.a.a.l.c0.a(Unknown Source:1)
	at g.b.a.j0.i.o(Unknown Source:4)
	at g.b.a.f0.w.f0$a.run(Unknown Source:8)
	... 7 more

**Comment by 0ranko0P** [comment]
Emmm... An exception happened when AutoDark reporting the real exception.
Would you mind catching a full log?

**Comment by NSTAdventure** [comment]
> Emmm... An exception happened when AutoDark reporting the real exception.
> Would you mind catching a full log?

bro my devices isn't rooted how i can catch full log?

**Comment by 0ranko0P** [comment]
> > Emmm... An exception happened when AutoDark reporting the real exception.
> > Would you mind catching a full log?
> 
> bro my devices isn't rooted how i can catch full log?

Run ```adb shell logcat *:W -v brief > log.txt``` in the terminal before starting AutoDark and pressing Ctrl+C after dark wallpaper page crash. No root required.

**Comment by NSTAdventure** [comment]
> > > Emmm... An exception happened when AutoDark reporting the real exception.
> > > Would you mind catching a full log?
> > 
> > 
> > bro my devices isn't rooted how i can catch full log?
> 
> Run `adb shell logcat *:W -v brief > log.txt` in the terminal before starting AutoDark and pressing Ctrl+C after dark wallpaper page crash. No root required.

dang it i guess this can be done via pc only

LADB cannot create log.txt

**Comment by NSTAdventure** [comment]
[log.txt](https://github.com/0ranko0P/AutoDark/files/6722387/log.txt)
log generated by adb on pc

**Comment by 0ranko0P** [comment]
> [log.txt](https://github.com/0ranko0P/AutoDark/files/6722387/log.txt)
> log generated by adb on pc

```
E/b       ( 9246): java.lang.SecurityException: Op READ_EXTERNAL_STORAGE ignore for package me.ranko.autodark
E/b       ( 9246): 	at android.os.Parcel.createException(Parcel.java:2087)
E/b       ( 9246): 	at android.os.Parcel.readException(Parcel.java:2055)
E/b       ( 9246): 	at android.os.Parcel.readException(Parcel.java:2003)
E/b       ( 9246): 	at android.app.IWallpaperManager$Stub$Proxy.getWallpaper(IWallpaperManager.java:801)
E/b       ( 9246): 	at android.app.WallpaperManager.getWallpaperFile(WallpaperManager.java:1022)
E/b       ( 9246): 	at android.app.WallpaperManager.getWallpaperFile(WallpaperManager.java:914)
E/b       ( 9246): 	at g.a.b.a.l.g(Unknown Source:20)
E/b       ( 9246): 	at g.a.b.a.x.b(Unknown Source:19)
E/b       ( 9246): 	at g.a.b.a.x.a(Unknown Source:6)
E/b       ( 9246): 	at g.a.b.a.x.call(Unknown Source:0)
E/b       ( 9246): 	at g.a.b.e.a.run(Unknown Source:2)
E/b       ( 9246): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/b       ( 9246): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/b       ( 9246): 	at java.lang.Thread.run(Thread.java:919)
```
It appears that the ColorOS did not grant actual storage permission to AutoDark.

**Comment by NSTAdventure** [comment]
> > [log.txt](https://github.com/0ranko0P/AutoDark/files/6722387/log.txt)
> > log generated by adb on pc
> 
> ```
> E/b       ( 9246): java.lang.SecurityException: Op READ_EXTERNAL_STORAGE ignore for package me.ranko.autodark
> E/b       ( 9246): 	at android.os.Parcel.createException(Parcel.java:2087)
> E/b       ( 9246): 	at android.os.Parcel.readException(Parcel.java:2055)
> E/b       ( 9246): 	at android.os.Parcel.readException(Parcel.java:2003)
> E/b       ( 9246): 	at android.app.IWallpaperManager$Stub$Proxy.getWallpaper(IWallpaperManager.java:801)
> E/b       ( 9246): 	at android.app.WallpaperManager.getWallpaperFile(WallpaperManager.java:1022)
> E/b       ( 9246): 	at android.app.WallpaperManager.getWallpaperFile(WallpaperManager.java:914)
> E/b       ( 9246): 	at g.a.b.a.l.g(Unknown Source:20)
> E/b       ( 9246): 	at g.a.b.a.x.b(Unknown Source:19)
> E/b       ( 9246): 	at g.a.b.a.x.a(Unknown Source:6)
> E/b       ( 9246): 	at g.a.b.a.x.call(Unknown Source:0)
> E/b       ( 9246): 	at g.a.b.e.a.run(Unknown Source:2)
> E/b       ( 9246): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> E/b       ( 9246): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> E/b       ( 9246): 	at java.lang.Thread.run(Thread.java:919)
> ```
> 
> It appears that the ColorOS did not grant actual storage permission to AutoDark.

nah no? i check use app ops that storage permission is allowed????
