### ISSUE TITLE
Last update adds nonfree component

### ISSUE THREAD

**Issue by IzzySoft** [0ranko0P/AutoDark#3]
Is there any reason you added GMS with the latest release? I guess GMS was plugged in by `com.google.android.gms.oss-licenses-plugin`. This taints an otherwise perfectly fine FOSS app with having non-foss components.

Some FOSS alternatives you might wish to consider:

* [SimpleLicenseDisplay](https://github.com/MarcDonald/SimpleLicenseDisplay) (MIT license)
* [LicensesDialog](https://github.com/PSDev/LicensesDialog) (Apache 2.0 license)

There are probalby more, these two are just the ones I've encountered already. The first one would even match your app's license.

Thanks for considering!

PS: in case you wonder what triggers non-foss here, see these <details><summary>Details</summary><pre>com/google/android/gms/auth/api/signin
com/google/android/gms/common/annotation
com/google/android/gms/common/api/internal
com/google/android/gms/common/internal
com/google/android/gms/common/util
com/google/android/gms/dynamite</pre></details>

**Comment by 0ranko0P** [comment]
Thanks a lot for your suggestion @IzzySoft , I will try these libraries.

**Comment by IzzySoft** [comment]
Great, thanks a lot! Good success and :crossed_fingers:

**Comment by 0ranko0P** [comment]
New version released, say goodbye to GMS!

**Comment by IzzySoft** [comment]
Yay, great – and my library scanner confirmed! So the "AntiFeature" flag will be gone [here](https://apt.izzysoft.de/fdroid/index/apk/me.ranko.autodark) with the next sync in approx. 3h. Thanks a lot!

Btw: Wouldn't you like to have your app listed at [F-Droid](https://f-droid.org/)? Now that there is no more "non-free dependency", it should be accepted there. If you want to, I gladly assist with the process (disclosure: I'm one of the F-Droid maintainers). In case you haven't heard of F-Droid before: TL;DR it's a catalog of pure free/libre & open-source apps with a very good name in the FOSS community. For a detailed description, be welcome to see e.g. my article (series) [F-Droid: The privacy-friendly alternative to Google Play Store](https://android.izzysoft.de/articles/named/fdroid-intro-1).

**Comment by 0ranko0P** [comment]
I read the article you wrote @IzzySoft , It would be great if my app list at the F-Droid! I will create a merge request on Gitlab soon after I reviewed the contribution doc and have a successful fdroid build.

**Comment by IzzySoft** [comment]
Thanks @0ranko0P – and great to hear! Ping me if you need help then. I'm not a packager, so I cannot help with build aspects, but I'm quite proficient in the metadata section (which are my task in the F-Droid team). One first pointer in that direction: establishing [Fastlane file structure](https://gitlab.com/snippets/1895688) in your repo here would be a great help :wink:

**Comment by 0ranko0P** [comment]
Unfortunately, my fdroid build failed, two of my dependencies are not whitelisted, the scanner report:
`ERROR: Found unknown maven repo 'https://dl.bintray.com/rikkaw/Shizuku' at build.gradle
ERROR: Found unknown maven repo 'https://dl.bintray.com/rikkaw/Libraries' at build.gradle`
So, is there a procedure I can put these in whitelist @IzzySoft ?

**Comment by IzzySoft** [comment]
Not in the easy run. Will be much easier finding those libraries in a Maven repo that is already whitelisted, see [trusted maven repos](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L99), or bringing them there. Alternatively you could include those libraries as Git sub-modules with your repo and implement their building with the build recipe. Or check if they could be set up as `srclib` in F-Droid (useful if they're needed by multiple apps and not available via any trusted Maven repo).

**Comment by NSTAdventure** [comment]
> Some FOSS alternatives you might wish to consider:
> 
> * [SimpleLicenseDisplay](https://github.com/MarcDonald/SimpleLicenseDisplay) (MIT license)
> * [LicensesDialog](https://github.com/PSDev/LicensesDialog) (Apache 2.0 license)

sorry what is that library for?

**Comment by IzzySoft** [comment]
To replace `com.google.android.gms.oss-licenses-plugin` (which drags in non-free components, as the initial post states)?
