### ISSUE TITLE
App Blacklist for root enforcement

### ISSUE THREAD

**Issue by Har-nick** [0ranko0P/AutoDark#6]
Would it be possible to implement an all blacklist to avoid AutoDark setting apps on fire? A search function included would also be great!

**Comment by 0ranko0P** [comment]
That's a good point, some old API apps indeed look awful in dark mode, but to achieve this function need AutoDark monitoring the foreground app with a lot of resources consumed.
The best option is the Xposed, And I will implement this function when EdXposed is stable enough on Android 10.

**Comment by HarnickA** [comment]
Awesome. I'm currently using EdXposed on Android 10, so I'd be up for testing if you need it. Though I haven't noticed and glitches on LineageOS so far.

**Comment by 0ranko0P** [comment]
A beta version just released, the blacklist works fine on EdXposed-SandHook, so it would be great if you can test on YAHFA @HarnickA .

**Comment by HarnickA** [comment]
Blacklist also works for me on YAHFA. Only issue I've found is that the blacklist doesn't list system apps.

**Comment by 0ranko0P** [comment]
That's expected behaviour, hook System apps is unnecessary: 
https://github.com/0ranko0P/AutoDark/blob/42886935ee2b53a99bec4291a1ab52d6fee6b264/app/src/main/java/me/ranko/autodark/xposed/XCore.kt#L85-L86
